"""initial

Revision ID: 7124a89174a2
Revises: 
Create Date: 2026-04-29 14:06:42.255037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7124a89174a2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_state',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('budget_overrides',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('effective_month', sa.String(), nullable=False),
    sa.Column('amount_usd', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_calls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('fallback', sa.Boolean(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('called_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.create_index('idx_llm_calls_month', ['called_at'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('closed_reason', sa.String(), nullable=True),
    sa.Column('drafted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voice_profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('profile_text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drafts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('telegram_message_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drafts', schema=None) as batch_op:
        batch_op.create_index('idx_drafts_status', ['status'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('github_id', sa.String(), nullable=False),
    sa.Column('repo', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('triage_score', sa.Float(), nullable=True),
    sa.Column('triage_reason', sa.Text(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('idx_events_repo_time', ['repo', 'occurred_at'], unique=False)
        batch_op.create_index('idx_events_session', ['session_id'], unique=False)

    op.create_table('decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('reject_reason', sa.String(), nullable=True),
    sa.Column('edited_text', sa.Text(), nullable=True),
    sa.Column('edit_diff', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=True),
    sa.Column('twitter_id', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('twitter_id')
    )
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('retweets', sa.Integer(), nullable=True),
    sa.Column('replies', sa.Integer(), nullable=True),
    sa.Column('bookmarks', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.create_index('idx_metrics_post', ['post_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.drop_index('idx_metrics_post')

    op.drop_table('metrics')
    op.drop_table('posts')
    op.drop_table('decisions')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('idx_events_session')
        batch_op.drop_index('idx_events_repo_time')

    op.drop_table('events')
    with op.batch_alter_table('drafts', schema=None) as batch_op:
        batch_op.drop_index('idx_drafts_status')

    op.drop_table('drafts')
    op.drop_table('voice_profile')
    op.drop_table('sessions')
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.drop_index('idx_llm_calls_month')

    op.drop_table('llm_calls')
    op.drop_table('budget_overrides')
    op.drop_table('bot_state')
    # ### end Alembic commands ###
